algoritmo "exercicio44"
var
   valorInicio, valorFinal, valorIncremento, contador: inteiro
inicio
   escreva("inicio da contagem: ")
   leia(valorInicio)
   escreva("final da contagem: ")
   leia(valorFinal)
   escreva("Valor do incremento: ")
   leia(valorIncremento)

   contador <- valorInicio
   enquanto (contador <= valorFinal) faca
      escreva(contador)
      contador <- contador + valorIncremento

   FimEnquanto
   escreva(" acabou!")


fimalgoritmo